#!/bin/bash

##########################################################################
#
#  Calls fairseq-interactive with a g2p model for standard pronunciation 
#  of Icelandic. See Readme.md for fairseq setup instructions.
#
#  The characters in the input words to transcribe have to be separated by space:
#    'h l a u p a'
#
#  Usage example: 
#    $cat wordlist.txt | ./transcribe_ice_standard wordlist_g2p_standard.out wordlist_g2p_standard.tsv
#
###########################################################################

# complete output file
OUT="$1" 
# results of the g2p
TSV="$2"

fairseq-interactive \
    "data-bin/standard" \
    --source-lang="standard.graphemes" \
    --target-lang="standard.phonemes" \
    --path="checkpoints/standard-256-.3-s-s/checkpoint_last.pt" \
    --seed=1917 \
    --beam=5 \
    --no-progress-bar \
     > "${OUT}"
        # Extracts the predictions into a TSV file.
        paste \
            <(cat "${OUT}" | grep '^S-' | cut -f2) \
            <(cat "${OUT}" | grep '^H-' | cut -f3) \
            > "${TSV}"
